export type Lang = "pt" | "en";

export const dict = {
  pt: {
    nav_services: "Serviços",
    nav_packages: "Pacotes",
    nav_process: "Processo",
    nav_faq: "FAQ",
    nav_contact: "Contacto",
    cta_primary: "Pedir Proposta",
    cta_secondary: "Ver Pacotes",

    hero_eyebrow: "Sites feitos à mão, para negócios com ambição",
    hero_title_a: "Presença digital",
    hero_title_b: "à medida do seu",
    hero_title_c: "negócio",
    hero_sub:
      "Construímos sites rápidos, bonitos e eficazes para pequenos negócios locais. Linguagem humana, preços transparentes, resultados reais.",
    hero_scroll: "Descer",

    audience_title: "Trabalhamos com",
    audience_1: "Cabeleireiros",
    audience_2: "Restaurantes",
    audience_3: "Clínicas",
    audience_4: "Lojas",
    audience_5: "Ginásios",
    audience_6: "Escritórios",

    services_eyebrow: "O que fazemos",
    services_title: "Tudo o que precisa para estar online",
    services_sub: "Funcionalidades pensadas para o dia a dia do seu negócio.",
    s1_title: "Sites Modernos",
    s1_desc: "Rápidos e bonitos em qualquer ecrã, do telemóvel ao computador.",
    s2_title: "Lojas Online",
    s2_desc: "Venda os seus produtos online com uma loja simples de gerir.",
    s3_title: "Formulários",
    s3_desc: "Receba mensagens dos clientes directamente no seu email.",
    s4_title: "Marcações Online",
    s4_desc: "Os clientes marcam serviços a qualquer hora, sem chamadas.",
    s5_title: "Aparecer no Google",
    s5_desc: "Configuramos o seu site para ser encontrado nas pesquisas.",
    s6_title: "Estatísticas",
    s6_desc: "Veja quantas pessoas visitam e o que procuram no seu site.",

    packages_eyebrow: "Pacotes e preços",
    packages_title: "Escolha o que faz sentido para si",
    packages_sub: "Preços claros, sem letra pequena, sem surpresas.",
    pop_badge: "Mais Popular",
    consult: "A consultar",
    per_year: "/ano",
    per_month: "/mês",

    p1_name: "Site Básico",
    p1_tag: "Para transmitir confiança e ser encontrado",
    p1_price: "desde 950€",
    p1_desc: "Site simples, moderno e profissional para transmitir confiança e facilitar o contacto.",
    p1_f1: "Páginas inicial, sobre e contactos",
    p1_f2: "Design adaptado a telemóvel",
    p1_f3: "SEO local básico",
    p1_f4: "Formulário de contacto",

    p2_name: "Site Profissional",
    p2_tag: "O mais escolhido por quem agenda clientes",
    p2_price: "desde 1.600€",
    p2_desc: "Tudo do Pacote 1 + sistema de marcações com confirmações e lembretes automáticos.",
    p2_f1: "Tudo o que está no Pacote Básico",
    p2_f2: "Marcações online com horários",
    p2_f3: "Vários tipos de serviço",
    p2_f4: "Confirmações e lembretes automáticos por email",
    p2_f5: "Painel para gerir marcações",
    p2_f6: "Apresentação profissional dos serviços",
    p2_f7: "",
    p2_f8: "",

    p3_name: "Loja Online",
    p3_tag: "Para vender e gerir encomendas",
    p3_price: "desde 3.500€",
    p3_desc: "Site completo com produtos, carrinho, pagamentos e gestão simples para a equipa.",
    p3_f1: "Catálogo de produtos e checkout",
    p3_f2: "Pagamentos integrados",
    p3_f3: "Gestão de encomendas",
    p3_f4: "Painel simples para a equipa",
    p3_f5: "Adaptado a telemóvel",
    p3_f6: "SEO local básico",
    p3_f7: "",
    p3_f8: "",

    p4_name: "Plataforma Empresarial",
    p4_tag: "Projecto à medida para operações complexas",
    p4_price: "desde 15.000€",
    p4_desc: "Projecto à medida com integrações, automações e perfis de acesso para operações complexas.",
    p4_f1: "Backend personalizado",
    p4_f2: "Múltiplos perfis de utilizador",
    p4_f3: "Integrações API",
    p4_f4: "Automações de processos",
    p4_f5: "Áreas privadas e permissões",
    p4_f6: "Acompanhamento dedicado",
    p4_f7: "",

    extras_title: "Serviços Extra",
    extras_sub: "Para complementar o seu pacote quando fizer sentido.",
    e1: "Site multilingue",
    e1_price: "150€ – 600€",
    e1_note: "Várias versões de idioma para atrair turistas, expatriados e clientes internacionais.",
    e2: "Gestão de SEO local",
    e2_price: "100€ – 250€/mês",
    e2_note: "Trabalho contínuo para aparecer quando alguém procura serviços na sua zona.",
    e3: "Gestão de Google Ads",
    e3_price: "200€ – 500€ + 200€ – 600€/mês",
    e3_note: "Campanhas pagas para visibilidade imediata em pesquisas com intenção de compra.",
    e4: "WhatsApp click-to-chat",
    e4_price: "50€ – 150€",
    e4_note: "Botão no site que abre directamente o WhatsApp da empresa.",
    e5: "Sistema de pagamentos",
    e5_price: "250€ – 500€",
    e5_note: "Ligação a pagamentos online para sinais, pré-pagamentos ou vendas simples.",
    e6: "Bot de IA para WhatsApp",
    e6_price: "250€ – 1.000€ + mensal",
    e6_note: "Assistente automático que responde às perguntas mais frequentes.",
    e7: "Integração com redes sociais",
    e7_price: "100€ – 200€",
    e7_note: "Liga o site aos perfis sociais e mostra que o negócio está activo.",
    e8: "Gestão de redes sociais",
    e8_price: "100€ – 250€/mês",
    e8_note: "Publicação regular de conteúdos para transformar o dia a dia numa montra digital.",
    e9: "Analytics e relatórios",
    e9_price: "100€ – 250€ + 50€ – 150€/mês",
    e9_note: "Saber, de forma clara, se o site está a trazer contactos e oportunidades.",

    process_eyebrow: "Como funciona",
    process_title: "Do primeiro olá ao site online",
    process_sub: "Cinco passos. Sem complicar.",
    step1_t: "Conversa Inicial",
    step1_d: "Falamos sobre o seu negócio e o que precisa.",
    step2_t: "Proposta",
    step2_d: "Enviamos uma proposta clara, com preços e prazos.",
    step3_t: "Criação",
    step3_d: "Desenhamos e construímos o site com atenção ao detalhe.",
    step4_t: "Revisão",
    step4_d: "Mostramos o site e fazemos os ajustes que pedir.",
    step5_t: "Lançamento",
    step5_d: "Colocamos o site online e ensinamos a usá-lo.",

    faq_eyebrow: "Dúvidas frequentes",
    faq_title: "Respondemos antes que pergunte",
    faq_q1: "Quanto tempo demora a fazer um site?",
    faq_a1:
      "Um site básico fica pronto em duas a três semanas. Um site profissional ou loja online demora entre quatro e seis semanas, dependendo do conteúdo que tenha disponível.",
    faq_q2: "Preciso de ter domínio e alojamento?",
    faq_a2:
      "Não precisa de tratar disso. Tratamos do registo do domínio e do alojamento por si. Se já tiver, ainda melhor — usamos o que já existe.",
    faq_q3: "Posso fazer alterações ao site depois?",
    faq_a3:
      "Pode. Pequenas alterações estão incluídas na manutenção opcional. Para mudanças maiores, fazemos sempre um orçamento simples primeiro.",
    faq_q4: "O site funciona bem em telemóveis?",
    faq_a4:
      "Todos os sites que fazemos são pensados primeiro para o telemóvel — onde a maioria dos seus clientes vai visitar.",
    faq_q5: "O que inclui a manutenção?",
    faq_a5:
      "Actualizações de segurança, pequenas alterações de conteúdo, backups regulares e apoio sempre que precisar — tudo por um valor mensal fixo.",
    faq_q6: "Como funcionam os pagamentos?",
    faq_a6:
      "50% no início, 50% na entrega. Para a Plataforma Empresarial podemos definir um plano de pagamentos ajustado ao projecto.",

    contact_eyebrow: "Vamos a isto",
    contact_title: "Conte-nos sobre o seu projecto",
    contact_sub:
      "Preencha em menos de um minuto. Respondemos no mesmo dia útil com uma proposta personalizada.",
    f_name: "Nome",
    f_name_ph: "Como gosta de ser tratado?",
    f_business: "Nome do negócio",
    f_business_ph: "O nome da sua loja, clínica, etc.",
    f_email: "Email",
    f_email_ph: "para onde respondemos",
    f_phone: "Telefone (opcional)",
    f_phone_ph: "se preferir uma chamada",
    f_package: "Qual pacote lhe interessa?",
    f_extras: "Extras que gostaria de incluir",
    f_topics: "Outros tópicos",
    f_topics_ph: "Conte-nos mais — ideias, exemplos que goste, dúvidas…",
    f_submit: "Enviar pedido",
    f_sent_title: "Recebido!",
    f_sent_desc:
      "Obrigado pelo seu contacto. Respondemos no próximo dia útil com uma proposta à medida.",
    f_required: "Campo obrigatório",
    f_invalid_email: "Email inválido",

    footer_tagline: "Presença digital com alma. Feita em Portugal.",
    footer_rights: "Todos os direitos reservados.",
    lang_label: "Idioma",
  },
  en: {
    nav_services: "Services",
    nav_packages: "Packages",
    nav_process: "Process",
    nav_faq: "FAQ",
    nav_contact: "Contact",
    cta_primary: "Request a Quote",
    cta_secondary: "See Packages",

    hero_eyebrow: "Handcrafted for ambitious businesses",
    hero_title_a: "A digital presence",
    hero_title_b: "tailored to your",
    hero_title_c: "business",
    hero_sub:
      "We build fast, beautiful, effective websites for local businesses. Plain language, transparent pricing, real results.",
    hero_scroll: "Scroll",

    audience_title: "We work with",
    audience_1: "Hair Salons",
    audience_2: "Restaurants",
    audience_3: "Clinics",
    audience_4: "Shops",
    audience_5: "Gyms",
    audience_6: "Offices",

    services_eyebrow: "What we do",
    services_title: "Everything you need to be online",
    services_sub: "Features built for the day-to-day of running a business.",
    s1_title: "Modern Websites",
    s1_desc: "Fast and beautiful on every screen, from phone to desktop.",
    s2_title: "Online Stores",
    s2_desc: "Sell your products online with a store that's easy to manage.",
    s3_title: "Forms",
    s3_desc: "Receive messages from customers straight into your inbox.",
    s4_title: "Online Bookings",
    s4_desc: "Clients book services any time of day, no phone calls needed.",
    s5_title: "Show Up on Google",
    s5_desc: "We set up your site so people can find it on search.",
    s6_title: "Analytics",
    s6_desc: "See how many people visit and what they're looking for.",

    packages_eyebrow: "Packages & pricing",
    packages_title: "Pick what makes sense for you",
    packages_sub: "Clear prices, no small print, no surprises.",
    pop_badge: "Most Popular",
    consult: "On request",
    per_year: "/yr",
    per_month: "/mo",

    p1_name: "Starter Site",
    p1_tag: "Build trust and be easy to reach",
    p1_price: "from €950",
    p1_desc: "A simple, modern, professional site that builds trust and makes contact easy.",
    p1_f1: "Home, About and Contact pages",
    p1_f2: "Mobile-first design",
    p1_f3: "Basic local SEO",
    p1_f4: "Contact form",

    p2_name: "Professional Site",
    p2_tag: "The favourite for booking-based businesses",
    p2_price: "from €1,600",
    p2_desc: "Everything from Package 1 plus a booking system with automatic confirmations and reminders.",
    p2_f1: "Everything in the Starter package",
    p2_f2: "Online bookings with time slots",
    p2_f3: "Multiple service types",
    p2_f4: "Automatic email confirmations and reminders",
    p2_f5: "Dashboard to manage bookings",
    p2_f6: "Professional service presentation",
    p2_f7: "",
    p2_f8: "",

    p3_name: "Online Store",
    p3_tag: "Sell and manage orders",
    p3_price: "from €3,500",
    p3_desc: "A full site with products, cart, payments and a simple management area for your team.",
    p3_f1: "Product catalogue and checkout",
    p3_f2: "Integrated payments",
    p3_f3: "Order management",
    p3_f4: "Simple dashboard for the team",
    p3_f5: "Mobile-friendly",
    p3_f6: "Basic local SEO",
    p3_f7: "",
    p3_f8: "",

    p4_name: "Enterprise Platform",
    p4_tag: "Bespoke build for complex operations",
    p4_price: "from €15,000",
    p4_desc: "A bespoke project with integrations, automations and access profiles for complex operations.",
    p4_f1: "Custom backend",
    p4_f2: "Multiple user profiles",
    p4_f3: "API integrations",
    p4_f4: "Process automations",
    p4_f5: "Private areas and permissions",
    p4_f6: "Dedicated support",
    p4_f7: "",

    extras_title: "Extras",
    extras_sub: "Add-ons to complement your package when it makes sense.",
    e1: "Multilingual site",
    e1_price: "€150 – €600",
    e1_note: "Multiple language versions to attract tourists, expats and international clients.",
    e2: "Local SEO management",
    e2_price: "€100 – €250/mo",
    e2_note: "Ongoing work so people find you when searching for services in your area.",
    e3: "Google Ads management",
    e3_price: "€200 – €500 + €200 – €600/mo",
    e3_note: "Paid campaigns for immediate visibility on high-intent searches.",
    e4: "WhatsApp click-to-chat",
    e4_price: "€50 – €150",
    e4_note: "A button on your site that opens the business WhatsApp directly.",
    e5: "Payment system",
    e5_price: "€250 – €500",
    e5_note: "Online payments for deposits, prepayments or simple sales without a full store.",
    e6: "AI WhatsApp bot",
    e6_price: "€250 – €1,000 + monthly",
    e6_note: "An automatic assistant that answers the most common questions.",
    e7: "Social media integration",
    e7_price: "€100 – €200",
    e7_note: "Links your site to social profiles and shows the business is active.",
    e8: "Social media management",
    e8_price: "€100 – €250/mo",
    e8_note: "Regular content so day-to-day work becomes a digital showcase.",
    e9: "Analytics & reporting",
    e9_price: "€100 – €250 + €50 – €150/mo",
    e9_note: "Clear view of whether the site is bringing in contacts and opportunities.",

    process_eyebrow: "How it works",
    process_title: "From hello to live website",
    process_sub: "Five steps. No fuss.",
    step1_t: "First Chat",
    step1_d: "We talk about your business and what you need.",
    step2_t: "Proposal",
    step2_d: "We send a clear proposal with prices and timelines.",
    step3_t: "Build",
    step3_d: "We design and build the site, with care for every detail.",
    step4_t: "Review",
    step4_d: "You see it, you ask for changes, we make them.",
    step5_t: "Launch",
    step5_d: "We put the site live and teach you how to use it.",

    faq_eyebrow: "Frequent questions",
    faq_title: "Answers before you ask",
    faq_q1: "How long does it take to build a website?",
    faq_a1:
      "A starter site is ready in two to three weeks. A professional site or online store takes four to six weeks, depending on the content you have ready.",
    faq_q2: "Do I need a domain and hosting?",
    faq_a2:
      "You don't have to worry about that. We handle the domain registration and hosting for you. If you already have them, even better — we use what's there.",
    faq_q3: "Can I make changes later?",
    faq_a3:
      "Yes. Small changes are included in optional maintenance. For bigger changes, we always send a simple quote first.",
    faq_q4: "Does it work well on phones?",
    faq_a4:
      "Every site we build is designed for the phone first — where most of your customers will see it.",
    faq_q5: "What does maintenance include?",
    faq_a5:
      "Security updates, small content edits, regular backups, and support whenever you need — all for a fixed monthly fee.",
    faq_q6: "How do payments work?",
    faq_a6:
      "50% to start, 50% on delivery. For the Enterprise Platform we can agree a payment plan tailored to the project.",

    contact_eyebrow: "Let's do this",
    contact_title: "Tell us about your project",
    contact_sub:
      "Takes under a minute. We reply within the next business day with a tailored proposal.",
    f_name: "Name",
    f_name_ph: "How should we call you?",
    f_business: "Business name",
    f_business_ph: "Your shop, clinic, studio…",
    f_email: "Email",
    f_email_ph: "where we should reply",
    f_phone: "Phone (optional)",
    f_phone_ph: "if you prefer a call",
    f_package: "Which package fits you?",
    f_extras: "Extras you'd like to add",
    f_topics: "Other topics",
    f_topics_ph: "Tell us more — ideas, examples you like, questions…",
    f_submit: "Send request",
    f_sent_title: "Got it!",
    f_sent_desc:
      "Thank you for reaching out. We'll reply the next business day with a tailored proposal.",
    f_required: "Required field",
    f_invalid_email: "Invalid email",

    footer_tagline: "Digital identity with soul. Made in Portugal.",
    footer_rights: "All rights reserved.",
    lang_label: "Language",
  },
} as const;

export type DictKey = keyof (typeof dict)["pt"];