export type Lang = "pt" | "en";

export const dict = {
  pt: {
    nav_services: "Serviços",
    nav_packages: "Pacotes",
    nav_process: "Processo",
    nav_faq: "FAQ",
    nav_contact: "Contacto",
    cta_primary: "Pedir Proposta",
    cta_secondary: "Ver Pacotes",

    hero_eyebrow: "Sites para negócios portugueses",
    hero_title_a: "Presença digital",
    hero_title_b: "à medida do seu",
    hero_title_c: "negócio",
    hero_sub:
      "Construímos sites rápidos, bonitos e eficazes para pequenos negócios locais. Linguagem humana, preços transparentes, resultados reais.",
    hero_scroll: "Descer",

    audience_title: "Trabalhamos com",
    audience_1: "Cabeleireiros",
    audience_2: "Restaurantes",
    audience_3: "Clínicas",
    audience_4: "Lojas",
    audience_5: "Ginásios",
    audience_6: "Escritórios",

    services_eyebrow: "O que fazemos",
    services_title: "Tudo o que precisa para estar online",
    services_sub: "Funcionalidades pensadas para o dia a dia do seu negócio.",
    s1_title: "Sites Modernos",
    s1_desc: "Rápidos e bonitos em qualquer ecrã, do telemóvel ao computador.",
    s2_title: "Lojas Online",
    s2_desc: "Venda os seus produtos online com uma loja simples de gerir.",
    s3_title: "Formulários",
    s3_desc: "Receba mensagens dos clientes directamente no seu email.",
    s4_title: "Marcações Online",
    s4_desc: "Os clientes marcam serviços a qualquer hora, sem chamadas.",
    s5_title: "Aparecer no Google",
    s5_desc: "Configuramos o seu site para ser encontrado nas pesquisas.",
    s6_title: "Estatísticas",
    s6_desc: "Veja quantas pessoas visitam e o que procuram no seu site.",

    packages_eyebrow: "Pacotes e preços",
    packages_title: "Escolha o que faz sentido para si",
    packages_sub: "Preços claros, sem letra pequena, sem surpresas.",
    pop_badge: "Mais Popular",
    consult: "A consultar",
    per_year: "/ano",
    per_month: "/mês",

    p1_name: "Site Básico",
    p1_tag: "Perfeito para começar",
    p1_price: "299€",
    p1_f1: "Até 3 páginas",
    p1_f2: "Adaptado a telemóvel",
    p1_f3: "Formulário de contacto",
    p1_f4: "Google Maps integrado",
    p1_f5: "Ligação às redes sociais",
    p1_f6: "Email profissional incluído",

    p2_name: "Site Profissional",
    p2_tag: "O mais escolhido",
    p2_price: "599€",
    p2_f1: "Até 6 páginas",
    p2_f2: "Adaptado a telemóvel",
    p2_f3: "Formulário avançado",
    p2_f4: "Marcação online",
    p2_f5: "Galeria de fotos",
    p2_f6: "Email profissional incluído",
    p2_f7: "Integração redes sociais",
    p2_f8: "Optimização para Google",

    p3_name: "Loja Online",
    p3_tag: "Para começar a vender",
    p3_price: "999€",
    p3_f1: "Até 50 produtos",
    p3_f2: "Pagamentos online",
    p3_f3: "Gestão de stock",
    p3_f4: "Cupões de desconto",
    p3_f5: "Cálculo de envios",
    p3_f6: "Email profissional incluído",
    p3_f7: "Optimização para Google",
    p3_f8: "Formação incluída",

    p4_name: "Plataforma Empresarial",
    p4_tag: "Soluções à medida",
    p4_price: "A consultar",
    p4_f1: "Páginas ilimitadas",
    p4_f2: "Funcionalidades à medida",
    p4_f3: "Área de clientes",
    p4_f4: "Integrações especiais",
    p4_f5: "Email profissional incluído",
    p4_f6: "Suporte prioritário",
    p4_f7: "Formação da equipa",

    extras_title: "Serviços Extra",
    extras_sub: "Para complementar o seu pacote quando fizer sentido.",
    e1: "Domínio (.pt ou .com)",
    e1_price: "15€/ano",
    e2: "Alojamento",
    e2_price: "10€/mês",
    e3: "Manutenção",
    e3_price: "30€/mês",
    e3_note: "Actualizações, pequenas alterações, backups e suporte.",
    e4: "Anúncios Google",
    e4_price: "A consultar",
    e5: "Gestão de Redes Sociais",
    e5_price: "A consultar",

    process_eyebrow: "Como funciona",
    process_title: "Do primeiro olá ao site online",
    process_sub: "Cinco passos. Sem complicar.",
    step1_t: "Conversa Inicial",
    step1_d: "Falamos sobre o seu negócio e o que precisa.",
    step2_t: "Proposta",
    step2_d: "Enviamos uma proposta clara, com preços e prazos.",
    step3_t: "Criação",
    step3_d: "Desenhamos e construímos o site com atenção ao detalhe.",
    step4_t: "Revisão",
    step4_d: "Mostramos o site e fazemos os ajustes que pedir.",
    step5_t: "Lançamento",
    step5_d: "Colocamos o site online e ensinamos a usá-lo.",

    faq_eyebrow: "Dúvidas frequentes",
    faq_title: "Respondemos antes que pergunte",
    faq_q1: "Quanto tempo demora a fazer um site?",
    faq_a1:
      "Um site básico fica pronto em duas a três semanas. Um site profissional ou loja online demora entre quatro e seis semanas, dependendo do conteúdo que tenha disponível.",
    faq_q2: "Preciso de ter domínio e alojamento?",
    faq_a2:
      "Não precisa de tratar disso. Tratamos do registo do domínio e do alojamento por si. Se já tiver, ainda melhor — usamos o que já existe.",
    faq_q3: "Posso fazer alterações ao site depois?",
    faq_a3:
      "Pode. Pequenas alterações estão incluídas na manutenção opcional. Para mudanças maiores, fazemos sempre um orçamento simples primeiro.",
    faq_q4: "O site funciona bem em telemóveis?",
    faq_a4:
      "Todos os sites que fazemos são pensados primeiro para o telemóvel — onde a maioria dos seus clientes vai visitar.",
    faq_q5: "O que inclui a manutenção?",
    faq_a5:
      "Actualizações de segurança, pequenas alterações de conteúdo, backups regulares e apoio sempre que precisar — tudo por um valor mensal fixo.",
    faq_q6: "Como funcionam os pagamentos?",
    faq_a6:
      "50% no início, 50% na entrega. Para a Plataforma Empresarial podemos definir um plano de pagamentos ajustado ao projecto.",

    contact_eyebrow: "Vamos a isto",
    contact_title: "Conte-nos sobre o seu projecto",
    contact_sub:
      "Preencha em menos de um minuto. Respondemos no mesmo dia útil com uma proposta personalizada.",
    f_name: "Nome",
    f_name_ph: "Como gosta de ser tratado?",
    f_business: "Nome do negócio",
    f_business_ph: "O nome da sua loja, clínica, etc.",
    f_email: "Email",
    f_email_ph: "para onde respondemos",
    f_phone: "Telefone (opcional)",
    f_phone_ph: "se preferir uma chamada",
    f_package: "Qual pacote lhe interessa?",
    f_extras: "Extras que gostaria de incluir",
    f_topics: "Outros tópicos",
    f_topics_ph: "Conte-nos mais — ideias, exemplos que goste, dúvidas…",
    f_submit: "Enviar pedido",
    f_sent_title: "Recebido!",
    f_sent_desc:
      "Obrigado pelo seu contacto. Respondemos no próximo dia útil com uma proposta à medida.",
    f_required: "Campo obrigatório",
    f_invalid_email: "Email inválido",

    footer_tagline: "Sites para pequenos negócios. Feitos à mão, em Portugal.",
    footer_rights: "Todos os direitos reservados.",
    lang_label: "Idioma",
  },
  en: {
    nav_services: "Services",
    nav_packages: "Packages",
    nav_process: "Process",
    nav_faq: "FAQ",
    nav_contact: "Contact",
    cta_primary: "Request a Quote",
    cta_secondary: "See Packages",

    hero_eyebrow: "Websites for Portuguese small businesses",
    hero_title_a: "A digital presence",
    hero_title_b: "tailored to your",
    hero_title_c: "business",
    hero_sub:
      "We build fast, beautiful, effective websites for local businesses. Plain language, transparent pricing, real results.",
    hero_scroll: "Scroll",

    audience_title: "We work with",
    audience_1: "Hair Salons",
    audience_2: "Restaurants",
    audience_3: "Clinics",
    audience_4: "Shops",
    audience_5: "Gyms",
    audience_6: "Offices",

    services_eyebrow: "What we do",
    services_title: "Everything you need to be online",
    services_sub: "Features built for the day-to-day of running a business.",
    s1_title: "Modern Websites",
    s1_desc: "Fast and beautiful on every screen, from phone to desktop.",
    s2_title: "Online Stores",
    s2_desc: "Sell your products online with a store that's easy to manage.",
    s3_title: "Forms",
    s3_desc: "Receive messages from customers straight into your inbox.",
    s4_title: "Online Bookings",
    s4_desc: "Clients book services any time of day, no phone calls needed.",
    s5_title: "Show Up on Google",
    s5_desc: "We set up your site so people can find it on search.",
    s6_title: "Analytics",
    s6_desc: "See how many people visit and what they're looking for.",

    packages_eyebrow: "Packages & pricing",
    packages_title: "Pick what makes sense for you",
    packages_sub: "Clear prices, no small print, no surprises.",
    pop_badge: "Most Popular",
    consult: "On request",
    per_year: "/yr",
    per_month: "/mo",

    p1_name: "Starter Site",
    p1_tag: "Perfect to get started",
    p1_price: "€299",
    p1_f1: "Up to 3 pages",
    p1_f2: "Mobile-friendly",
    p1_f3: "Contact form",
    p1_f4: "Google Maps integrated",
    p1_f5: "Social media links",
    p1_f6: "Professional email included",

    p2_name: "Professional Site",
    p2_tag: "The most chosen",
    p2_price: "€599",
    p2_f1: "Up to 6 pages",
    p2_f2: "Mobile-friendly",
    p2_f3: "Advanced form",
    p2_f4: "Online bookings",
    p2_f5: "Photo gallery",
    p2_f6: "Professional email included",
    p2_f7: "Social media integration",
    p2_f8: "Google optimisation",

    p3_name: "Online Store",
    p3_tag: "Start selling online",
    p3_price: "€999",
    p3_f1: "Up to 50 products",
    p3_f2: "Online payments",
    p3_f3: "Stock management",
    p3_f4: "Discount coupons",
    p3_f5: "Shipping calculator",
    p3_f6: "Professional email included",
    p3_f7: "Google optimisation",
    p3_f8: "Training included",

    p4_name: "Enterprise Platform",
    p4_tag: "Custom solutions",
    p4_price: "On request",
    p4_f1: "Unlimited pages",
    p4_f2: "Custom features",
    p4_f3: "Client area",
    p4_f4: "Special integrations",
    p4_f5: "Professional email included",
    p4_f6: "Priority support",
    p4_f7: "Team training",

    extras_title: "Extras",
    extras_sub: "Add-ons to complement your package when it makes sense.",
    e1: "Domain (.pt or .com)",
    e1_price: "€15/yr",
    e2: "Hosting",
    e2_price: "€10/mo",
    e3: "Maintenance",
    e3_price: "€30/mo",
    e3_note: "Updates, small edits, backups and support.",
    e4: "Google Ads",
    e4_price: "On request",
    e5: "Social Media Management",
    e5_price: "On request",

    process_eyebrow: "How it works",
    process_title: "From hello to live website",
    process_sub: "Five steps. No fuss.",
    step1_t: "First Chat",
    step1_d: "We talk about your business and what you need.",
    step2_t: "Proposal",
    step2_d: "We send a clear proposal with prices and timelines.",
    step3_t: "Build",
    step3_d: "We design and build the site, with care for every detail.",
    step4_t: "Review",
    step4_d: "You see it, you ask for changes, we make them.",
    step5_t: "Launch",
    step5_d: "We put the site live and teach you how to use it.",

    faq_eyebrow: "Frequent questions",
    faq_title: "Answers before you ask",
    faq_q1: "How long does it take to build a website?",
    faq_a1:
      "A starter site is ready in two to three weeks. A professional site or online store takes four to six weeks, depending on the content you have ready.",
    faq_q2: "Do I need a domain and hosting?",
    faq_a2:
      "You don't have to worry about that. We handle the domain registration and hosting for you. If you already have them, even better — we use what's there.",
    faq_q3: "Can I make changes later?",
    faq_a3:
      "Yes. Small changes are included in optional maintenance. For bigger changes, we always send a simple quote first.",
    faq_q4: "Does it work well on phones?",
    faq_a4:
      "Every site we build is designed for the phone first — where most of your customers will see it.",
    faq_q5: "What does maintenance include?",
    faq_a5:
      "Security updates, small content edits, regular backups, and support whenever you need — all for a fixed monthly fee.",
    faq_q6: "How do payments work?",
    faq_a6:
      "50% to start, 50% on delivery. For the Enterprise Platform we can agree a payment plan tailored to the project.",

    contact_eyebrow: "Let's do this",
    contact_title: "Tell us about your project",
    contact_sub:
      "Takes under a minute. We reply within the next business day with a tailored proposal.",
    f_name: "Name",
    f_name_ph: "How should we call you?",
    f_business: "Business name",
    f_business_ph: "Your shop, clinic, studio…",
    f_email: "Email",
    f_email_ph: "where we should reply",
    f_phone: "Phone (optional)",
    f_phone_ph: "if you prefer a call",
    f_package: "Which package fits you?",
    f_extras: "Extras you'd like to add",
    f_topics: "Other topics",
    f_topics_ph: "Tell us more — ideas, examples you like, questions…",
    f_submit: "Send request",
    f_sent_title: "Got it!",
    f_sent_desc:
      "Thank you for reaching out. We'll reply the next business day with a tailored proposal.",
    f_required: "Required field",
    f_invalid_email: "Invalid email",

    footer_tagline: "Websites for small businesses. Handcrafted in Portugal.",
    footer_rights: "All rights reserved.",
    lang_label: "Language",
  },
} as const;

export type DictKey = keyof (typeof dict)["pt"];